export const QUERY_KEYS = {
  PROFILE: "profile",
  USER_BY_ID: "user-by-id",
  LOCATIONS: "locations",
  CATEGORIES: "categories",
  ADMIN_USERS: "admin-users",
  ADMIN_RENTS: "admin-rents",
  ADMIN_RENT_BY_ID: "admin-rent-by-id",
  ADMIN_CATEGORIES: "admin-categories",
  ADMIN_CATEGORY_BY_ID: "admin-category-by-id",
  ADMIN_LOCATIONS: "admin-locations",
  ADMIN_LOCATION_BY_ID: "admin-location-by-id",
  RECOMMENDED_RENTS: "rents-recommended",
  RENT_LIST: "rent-list",
  FAVORITE_RENT_LIST: "favorite-rent-list",
  RENT_POPULAR_LIST: "rent-popular-list",
  RENT_BY_ID: "rent-by-id",
  RENT_DETAIL_REVIEWS: "rent-detail-reviews",
  RESERVATIONS: "reservations",
  ADMİN_RESERVATIONS: "admin-reservations",
  ADMIN_REVIEWS: "admin-reviews",
};
